language: r
r:
  - 3.1
  - 3.2
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

cache: packages
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email: false
